def img
pipeline {
    environment {
        dockerHub = "alejandrognway/python-jenkins"
        dockerHubCredentials = 'docker-hub-login'
        dockerImage = ''
    }

    agent { dockerfile true }

    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }

        stage("Test"){
            steps {
                println("Running some tests ... pass")
            }
        }

        stage("Push to Docker Hub"){
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com ', dockerHubCredentials) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}